name: Build Test

on:
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.1

    - name: Build the application
      run: go build -v ./...

    - name: Test
      run: go run . -version
